
package GT_ECM2_MoFInjDat_phi.stim;

import java.util.List;
import org.apache.log4j.Logger;
import com.continental.gt.devices.Device;
import com.continental.gt.util.UtilExceptions;

import com.continental.gt.devices.Hil;
import com.continental.gt.test.stim.StimScenario;
import java.lang.InterruptedException;
import org.apache.thrift.TException;
import com.continental.gt.test.alias.writable.AliasHilParam;

/**
 * Test of stubbed class generated
 * Generated by GreenT
 */
public class StimScenario_0_CALC_MODE_ROAD_VS_20041 extends StimScenario {
	private Logger log = Logger.getLogger(StimScenario_0_CALC_MODE_ROAD_VS_20041.class);
	
	private Hil hil;
	
	public StimScenario_0_CALC_MODE_ROAD_VS_20041(){
		super("Anonymous StimScenario_0_CALC_MODE_ROAD_VS_20041");
	}

	public StimScenario_0_CALC_MODE_ROAD_VS_20041(String name) {
		super(name);
	}
	
	@Override
	public void addAllRequiredAlias() {			
	
		addAliasWritable(Hil.class,  "ROAD_MODE_VS_REGUL");
		addAliasWritable(Hil.class,  "HIL_VS_SP");
		addAliasWritable(Hil.class,  "HIL_KEY");
		addAliasWritable(Hil.class,  "PLA_C_KEY_PSN");
	}
	/* 
	 * @see com.continental.gt.test.stim.StimScenario#exec()
	 * Generated by GreenT.
	 */
	@Override
	public void exec(List<Device> devices) throws TException, InterruptedException {
		
		showMsg(".exec() : executing stimulation code of StimScenario_0_CALC_MODE_ROAD_VS_20041 class...");
		hil = (Hil)getDeviceByClass(devices, Hil.class);
			
		((AliasHilParam)hil.getAliasWritableByName("HIL_KEY")).setPhy((double) 1, hil);
		((AliasHilParam)hil.getAliasWritableByName("ROAD_MODE_VS_REGUL")).setPhy((double) 0, hil);
		((AliasHilParam)hil.getAliasWritableByName("PLA_C_KEY_PSN")).setPhy((double) 1, hil);
		delay(5);
		((AliasHilParam)hil.getAliasWritableByName("PLA_C_KEY_PSN")).setPhy((double) 0, hil);
		delay(1);
		((AliasHilParam)hil.getAliasWritableByName("HIL_VS_SP")).setPhy((double) 200, hil);
		delay(40);
		((AliasHilParam)hil.getAliasWritableByName("HIL_VS_SP")).setPhy((double) 0, hil);
		((AliasHilParam)hil.getAliasWritableByName("HIL_KEY")).setPhy((double) 0, hil);
		delay(20);
		
		showMsg("... complete ok!");
	}

	
}
