package com.continental.gt.generation.test;

import com.continental.gt.test.GreenTTest;
import com.continental.gt.test.report.Severity;
import com.continental.gt.test.alias.AliasReadable;

import org.apache.thrift.TException;	

/**
 * Test of stubbed class generated
 * Generated by GreenT
 */
public class GreenTTest_AIRT_Air_uRawTCACDsB2 extends GreenTTest {
	
	public GreenTTest_AIRT_Air_uRawTCACDsB2() {
		super("Anonymous GreenTTest_AIRT_Air_uRawTCACDsB2");
	}

	public GreenTTest_AIRT_Air_uRawTCACDsB2(String name) {
		super(name);
	}
	
	@Override
	public void addAllRequiredContextualData() {
		addRecordedVariable(new AliasReadable("Air_uRawTCACDsB2"));
		addRecordedVariable(new AliasReadable("HIL_VB_OUT"));
		addRecordedVariable(new AliasReadable("HIL_KEY_OUT"));
	}

	@Override
	public void createReport() {
		report.setVariableLongName("Sensed value of down stream charged air temperature (bank-2)");
		report.setVariableName("Air_uRawTCACDsB2");
		report.setResponsible("D.Matichard (FSD ALTEN09)");
		report.setSeverity(Severity.LOW);
		report.setTestSummary("Test if the interface Air_uRawTCACDsB2 is correctly stub to 0");
		
		report.addComment("");
		report.addComment("");
		report.addComment("");
	}

	@Override
	public void verdict() {
		// TODO Auto-generated method stub
		
	}
}
